import { auth, db } from "./firebase.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { doc, getDoc, setDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

// Full player list
const players = [
  {name:"CHIBUIKE SUCCESS", position:"FWD", price:10},
  {name:"OKOYE NELSON", position:"GK", price:9.5},
  {name:"NNADOZIE DESTINY", position:"GK", price:10.5},
  {name:"UKONU ANOINTING", position:"DEF", price:15},
  {name:"IBE EMMANUEL", position:"MID", price:5},
  {name:"NWANKWO OSITA", position:"MID", price:10},
  {name:"JAMES NKWUMAH", position:"DEF", price:5},
  {name:"OKONKWO GERARD", position:"DEF", price:5},
  {name:"NNAJI MICHAEL", position:"MID", price:8},
  {name:"IHEANACHO PRAISE", position:"FWD", price:5},
  {name:"CHIAMAEZE OWN", position:"FWD", price:10},
  {name:"EZUEGO ENU", position:"MID", price:10},
  {name:"MAC DONALD", position:"MID", price:10},
  {name:"OKWUDIRI SOLOMON", position:"DEF", price:10},
  {name:"EKE EMMANUEL", position:"MID", price:7.5},
  {name:"EMOLE JULES", position:"MID", price:7},
  {name:"NNONA KELVIN", position:"DEF", price:15},
  {name:"EGEMOLE HENRY", position:"MID", price:10},
  {name:"UZOMA PERFECT", position:"MID", price:8},
  {name:"IBEZUE CHINEDU", position:"DEF", price:8},
  {name:"ONUOHA OSCAR", position:"DEF", price:8.5},
  {name:"NNADOZIE DIVINE", position:"GK", price:10},
  {name:"OKOYE VICTOR", position:"GK", price:11},
  {name:"ILLONA PRINCEWILL", position:"MID", price:11},
  {name:"OPARA JOHNSON", position:"DEF", price:12},
  {name:"CHIBUIKE FAITHFUL", position:"MID", price:8},
  {name:"IFEJIAGWA IKECHUKWU", position:"MID", price:20},
  {name:"ENUKA RAMSEY", position:"MID", price:4},
  {name:"UDOH KENNETH", position:"MID", price:10},
  {name:"UWANDU DELIGHT", position:"MID", price:4.5},
  {name:"KINGSLEY IBEZUE", position:"DEF", price:10},
  {name:"NDUISI SUCCESS", position:"MID", price:10},
  {name:"EGBE BETHEL", position:"DEF", price:12},
  {name:"IGBONACHO SIXTUS", position:"MID", price:14},
  {name:"JOSEPH PROSPER", position:"MID", price:10},
  {name:"AUGUSTIN OKECHUKWU", position:"DEF", price:10},
  {name:"OKEZIE DAVID", position:"DEF", price:10},
  {name:"ONYEMA VICTOR", position:"MID", price:10},
  {name:"NWANKWO CHUKWUEMEKA", position:"MID", price:13},
  {name:"MICHAEL ANUDU
